include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
# there is no settingsreset (needed) for the XIAO

---
include:
  - board: planck_rev6
  - board: corneish_zen_v2_left
  - board: corneish_zen_v2_right
  - board: glove80_lh
  - board: glove80_rh
  - board: totem